### ISSUE TITLE
issue1

### ISSUE THREAD

**Issue by kmg159753** [Domae-back-end/hanghae99-curd#1]
1.Exceoption을 커스텀해서 에러코드를 던지는 방식을 사용하는 방식, JsonResponse 클래스에서 Generic을 사용해서 다양한 Request를 받는 부분을 많이 참고했다.  
2. RequestBody를 통해 json 형식으로 request를 받을때 데이터 하나만을 주기위해서 Map을 사용한다는 점도 배웠습니다.

**Comment by Domae-back-end** [comment]
감사합니다 !
